<%--
  Created by IntelliJ IDEA.
  User: Administrator
  Date: 2018\7\7 0007
  Time: 21:50
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
     <table>
         <tr>
             <td>类名</td>
             <td>注释</td>
         </tr>
         <tr>
             <td>Product</td>
             <td>商品表</td>
         </tr>
         <tr>
           <td>ProductCategory</td>
           <td>商品分类表</td>
        </tr>
         <tr>
             <td>ProductImages</td>
             <td>商品图片表</td>
         </tr>
         <tr>
             <td>Brand</td>
             <td>商品品牌表</td>
         </tr>
         <tr>
             <td>Review</td>
             <td>商品评论表</td>
         </tr>
         <tr>
             <td>Tag</td>
             <td>标签表</td>
         </tr>
         <tr>
             <td>Member</td>
             <td>会员主表</td>
         </tr>
         <tr>
             <td>Specification</td>
             <td>规格表</td>
         </tr>
         <tr>
             <td>Promotion</td>
             <td>促销表</td>
         </tr>
         <tr>
             <td>Cart</td>
             <td>购物车表</td>
         </tr>
         <tr>
             <td>？？</td>
             <td>购物车项表</td>
         </tr>
         <tr>
             <td>MemberRank</td>
             <td>会员价格表</td>
         </tr>
         <tr>
             <td>Order</td>
             <td>订单表</td>
         </tr>
         <tr>
             <td>Parameter</td>
             <td>商品参数表</td>
         </tr>
         <tr>
             <td>Consultation</td>
             <td>咨询表</td>
         </tr>
         <tr>
             <td>PaymentMethod</td>
             <td>支付方式表</td>
         </tr>
         <tr>
             <td>ShippingMethod</td>
             <td>配送方式表</td>
         </tr>
         <tr>
             <td>DeliveryCorp</td>
             <td>物流公司表</td>
         </tr>
         <tr>
             <td>Role</td>
             <td>角色表</td>
         </tr>
         <tr>
             <td>Admin</td>
             <td>管理员表</td>
         </tr>
         <tr>
             <td>CouponCode</td>
             <td>优惠码表</td>
         </tr>
         <tr>
             <td>Coupon</td>
             <td>优惠券表</td>
         </tr>
         <tr>
             <td>OrderItem</td>
             <td>订单项表</td>
         </tr>
         <tr>
             <td>OrderLog</td>
             <td>订单日志表</td>
         </tr>
         <tr>
             <td>Deposit</td>
             <td>预存款表</td>
         </tr>
         <tr>
             <td>Payment</td>
             <td>收款单表</td>
         </tr>
         <tr>
             <td>Refunds</td>
             <td>退款单表</td>
         </tr>
         <tr>
             <td>Shipping</td>
             <td>发货单表</td>
         </tr>
         <tr>
             <td>Returns</td>
             <td>退货单表</td>
         </tr>
         <tr>
             <td>Receiver</td>
             <td>收货地址表</td>
         </tr>
         <tr>
             <td>Area</td>
             <td>地区表</td>
         </tr>
         <tr>
             <td>DeliveryCenter</td>
             <td>发货点表</td>
         </tr>
         <tr>
             <td>ProductNotify</td>
             <td>到货通知表</td>
         </tr>
         <tr>
             <td>Message</td>
             <td>消息表</td>
         </tr>
         <tr>
             <td>Seo</td>
             <td>Seo设置表</td>
         </tr>
         <tr>
             <td>Log</td>
             <td>日志管理表</td>
         </tr>
         <tr>
             <td>MemberAttribute</td>
             <td>会员注册项表</td>
         </tr>
         <tr>
             <td>Navigation</td>
             <td>导航管理表</td>
         </tr>
         <tr>
             <td>FriendLink</td>
             <td>友情链接表</td>
         </tr>
         <tr>
             <td>AdvertisementPosition</td>
             <td>广告位表</td>
         </tr>
         <tr>
             <td>Advertisement</td>
             <td>广告管理表</td>
         </tr>
         <tr>
             <td>Article</td>
             <td>文章表</td>
         </tr>
         <tr>
             <td>ArticleCategory</td>
             <td>文章分类表</td>
         </tr>
         <tr>
             <td>DeliveryTemplate</td>
             <td>快递单模板表</td>
         </tr>
         <tr>
             <td>Attribute</td>
             <td>商品属性表</td>
         </tr>



     </table>
</body>
</html>
